# Generated by Django 6.0.5 on 2026-05-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('suspicious', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
